import { Address } from './address';
export interface PropertyData {
    archiveId: string;
    autonomousRegion: string;
    bedNumber: number | null;
    billingContactId: string | null;
    buildingPrice: Price;
    cadastreNumber: string;
    cadastreRef: string;
    cadastreUrl: string;
    cadastreValue: Price;
    comments?: string;
    contactPersonId: string;
    federalState: string;
    furniturePrice: Price;
    furniturePriceGross: Price;
    furniturePriceIVA: Price;
    furniturePriceIVAPercentage: number;
    furniturePriceTotal: Price;
    furniturePriceTPO: Price;
    furniturePriceTPOPercentage: number;
    garbageCollection: number;
    garbageCollectionDate: string | null;
    garbagePriceAmount: Price;
    ibiAmount: Price;
    ibiCollection: number;
    ibiCollectionDate: string | null;
    id: string;
    loanPrice: Price;
    mainOwnerId: string;
    mainOwnerType: string;
    mainPropertyId: string | null;
    municipality: string;
    name: string;
    plotPrice: Price;
    priceTotal: Price;
    propertyAddress: Address;
    propertyScanMail: string;
    purchaseDate: string | null;
    purchasePriceAJD: Price;
    purchasePriceAJDPercentage: number | null;
    purchasePriceGross: Price;
    purchasePriceNet: Price;
    purchasePriceTax: Price;
    purchasePriceTaxPercentage: number | null;
    purchasePriceTotal: Price;
    purchasePriceTPO: Price;
    purchasePriceTPOPercentage: number | null;
    saleDate: string | null;
    salePrice: Price;
    totalPrice: Price;
    type: string;
    typeOfUse: number[];
    year: number | null;
}

interface Price {
    currency?: string;
    value: number;
}
